server:
  port: 8080

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: false

config:
  userAgent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com
  webinterface login: root
  webinterfacepassword: 1234
  webinterface: /admin
  sites:
    - url: http://www.playback.ru/
      name: PlayBack.Ru
    - url: https://volochek.life/
      name: volochek
    - url: http://radiomv.ru/
      name: radiomv
    - url: https://ipfran.ru/
      name: ipfran
    - url: https://dimonvideo.ru/
      name: dimonvideo
    - url: https://nikoartgallery.com/
      name: nikoartgallery
    - url: https://et-cetera.ru/mobile/
      name: et-cetera
    - url: https://www.lutherancathedral.ru/
      name: lutherancathedral
    - url: https://dombulgakova.ru/
      name: dombulgakova
    - url: https://www.svetlovka.ru/
      name: svetlovka
    - url: https://www.skillbox.ru
      name: Skillbox


